"""add starter_id to pvp_games

Revision ID: 366e6e759667
Revises: 6ba9518fe960
Create Date: 2026-01-18 12:34:08.658777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '366e6e759667'
down_revision: Union[str, Sequence[str], None] = '6ba9518fe960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pvp_games', sa.Column('starter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pvp_games', 'users', ['starter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pvp_games', type_='foreignkey')
    op.drop_column('pvp_games', 'starter_id')
    # ### end Alembic commands ###
