"""update_schema_for_polymorphic_games

Revision ID: 3bf2de6eeff3
Revises: 7dd0459dd0e3
Create Date: 2026-01-17 15:48:59.846789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf2de6eeff3'
down_revision: Union[str, Sequence[str], None] = '7dd0459dd0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=False),
    sa.Column('player1_name', sa.String(), nullable=True),
    sa.Column('player1_secret', sa.String(length=4), nullable=True),
    sa.Column('player1_guesses', sa.JSON(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('game_type', sa.String(), nullable=True))
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_constraint(op.f('games_user_id_fkey'), 'games', type_='foreignkey')
    op.drop_column('games', 'secret')
    op.drop_column('games', 'user_id')
    op.drop_column('games', 'guesses')
    op.drop_column('games', 'player_secret')
    op.drop_column('games', 'ai_guesses')
    op.drop_column('games', 'completed_at')
    op.drop_column('games', 'opponent_type')
    op.drop_column('games', 'game_mode')
    op.drop_column('games', 'won')
    op.drop_column('games', 'attempts')
    op.drop_column('games', 'created_at')
    op.add_column('pvp_games', sa.Column('player1_name', sa.String(), nullable=True))
    op.add_column('pvp_games', sa.Column('player2_name', sa.String(), nullable=True))
    op.add_column('pvp_games', sa.Column('game_mode', sa.String(), nullable=False))
    op.add_column('pvp_games', sa.Column('ai_difficulty', sa.String(), nullable=True))
    op.drop_index(op.f('ix_pvp_games_id'), table_name='pvp_games')
    op.create_foreign_key(None, 'pvp_games', 'games', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pvp_games', type_='foreignkey')
    op.create_index(op.f('ix_pvp_games_id'), 'pvp_games', ['id'], unique=False)
    op.drop_column('pvp_games', 'ai_difficulty')
    op.drop_column('pvp_games', 'game_mode')
    op.drop_column('pvp_games', 'player2_name')
    op.drop_column('pvp_games', 'player1_name')
    op.add_column('games', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('won', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('game_mode', sa.VARCHAR(), server_default=sa.text("'single'::character varying"), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('opponent_type', sa.VARCHAR(), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('ai_guesses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('player_secret', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('guesses', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('secret', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('games_user_id_fkey'), 'games', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.drop_column('games', 'game_type')
    op.drop_table('single_games')
    # ### end Alembic commands ###
