"""add_elo_to_player_state

Revision ID: 6ba9518fe960
Revises: 3bf2de6eeff3
Create Date: 2026-01-17 18:11:53.892890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba9518fe960'
down_revision: Union[str, Sequence[str], None] = '3bf2de6eeff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('pvp_games', sa.Column('player1_elo', sa.Integer(), nullable=True))
    op.add_column('pvp_games', sa.Column('player2_elo', sa.Integer(), nullable=True))
    op.add_column('single_games', sa.Column('player1_elo', sa.Integer(), nullable=True))

    # Populate existing rows with default ELO (1200)
    op.execute("UPDATE pvp_games SET player1_elo = 1200 WHERE player1_elo IS NULL")
    op.execute("UPDATE pvp_games SET player2_elo = 1200 WHERE player2_elo IS NULL AND player2_id IS NOT NULL")
    op.execute("UPDATE single_games SET player1_elo = 1200 WHERE player1_elo IS NULL")

    # Make player1_elo non-nullable (player2_elo stays nullable since player2 might not exist yet)
    op.alter_column('pvp_games', 'player1_elo', nullable=False)
    op.alter_column('single_games', 'player1_elo', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_games', 'player1_elo')
    op.drop_column('pvp_games', 'player2_elo')
    op.drop_column('pvp_games', 'player1_elo')
    # ### end Alembic commands ###
